/*
 * Copyright 2026 Jason Monk
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Originally based on CodeMirror 6 by Marijn Haverbeke, licensed under MIT.
 * See NOTICE file for details.
 */
@file:Suppress("ktlint:standard:max-line-length")

package com.monkopedia.kodemirror.lang.sql

import com.monkopedia.kodemirror.language.FoldRange
import com.monkopedia.kodemirror.language.LRLanguage
import com.monkopedia.kodemirror.language.continuedIndent
import com.monkopedia.kodemirror.language.foldNodeProp
import com.monkopedia.kodemirror.language.indentNodeProp
import com.monkopedia.kodemirror.lezer.lr.LRParser
import com.monkopedia.kodemirror.lezer.lr.ParserConfig
import com.monkopedia.kodemirror.lezer.lr.ParserSpec
import com.monkopedia.kodemirror.lezer.lr.TokenizerReplacement

// The base parser (grammar-level, without style props).
// Generated by lezer-generator from the SQL grammar.
private val parserBase: LRParser = LRParser.deserialize(
    ParserSpec(
        version = 14,
        states = "%vQ]QQOOO#wQRO'#DSO\$OQQO'#CwO%eQQO'#CxO%lQQO'#CyO%sQQO'#CzOOQQ'#DS'#DSOOQQ'#C}'#C}O'UQRO'#C{OOQQ'#Cv'#CvOOQQ'#C|'#C|Q]QQOOQOQQOOO'`QQO'#DOO(xQRO,59cO)PQQO,59cO)UQQO'#DSOOQQ,59d,59dO)cQQO,59dOOQQ,59e,59eO)jQQO,59eOOQQ,59f,59fO)qQQO,59fOOQQ-E6{-E6{OOQQ,59b,59bOOQQ-E6z-E6zOOQQ,59j,59jOOQQ-E6|-E6|O+VQRO1G.}O+^QQO,59cOOQQ1G/O1G/OOOQQ1G/P1G/POOQQ1G/Q1G/QP+kQQO'#C}O+rQQO1G.}O)PQQO,59cO,PQQO'#Cw",
        stateData = ",[~OtOSPOSQOS~ORUOSUOTUOUUOVROXSOZTO]XO^QO_UO`UOaPObPOcPOdUOeUOfUOgUOhUO~O^]ORvXSvXTvXUvXVvXXvXZvX]vX_vX`vXavXbvXcvXdvXevXfvXgvXhvX~OsvX~P!jOa_Ob_Oc_O~ORUOSUOTUOUUOVROXSOZTO^tO_UO`UOa`Ob`Oc`OdUOeUOfUOgUOhUO~OWaO~P\$ZOYcO~P\$ZO[eO~P\$ZORUOSUOTUOUUOVROXSOZTO^QO_UO`UOaPObPOcPOdUOeUOfUOgUOhUO~O]hOsoX~P%zOajObjOcjO~O^]ORkaSkaTkaUkaVkaXkaZka]ka_ka`kaakabkackadkaekafkagkahka~Oska~P'kO^]O~OWvXYvX[vX~P!jOWnO~P\$ZOYoO~P\$ZO[pO~P\$ZO^]ORkiSkiTkiUkiVkiXkiZki]ki_ki`kiakibkickidkiekifkigkihki~Oski~P)xOWkaYka[ka~P'kO]hO~P\$ZOWkiYki[ki~P)xOasObsOcsO~O",
        goto = "#hwPPPPPPPPPPPPPPPPPPPPPPPPPPx||||!Y!^!d!xPPP#[TYOZeUORSTWZbdfqT[OZQZORiZSWOZQbRQdSQfTZgWbdfqQ^PWk^lmrQl_Qm`RrseVORSTWZbdfq",
        nodeNames = "\u26A0 LineComment BlockComment String Number Bool Null ( ) { } [ ] ; . Operator Punctuation SpecialVar Identifier QuotedIdentifier Keyword Type Bits Bytes Builtin Script Statement CompositeIdentifier Parens Braces Brackets Statement",
        maxTerm = 38,
        nodeProps = listOf(
            listOf("isolate", -4, 1, 2, 3, 19, "")
        ),
        propSources = listOf(sqlHighlighting),
        skippedNodes = listOf(0, 1, 2),
        repeatNodeCount = 3,
        tokenData = "RORO",
        tokenizers = listOf(0, tokens),
        topRules = mapOf("Script" to listOf(0, 25)),
        tokenPrec = 0
    )
)

/**
 * The configured SQL parser, with indentation, folding, and style props applied.
 * This is the base parser used by all SQL dialects (the tokenizer is swapped per-dialect).
 */
internal val sqlParser: LRParser = parserBase.configure(
    ParserConfig(
        props = listOf(
            indentNodeProp.add(
                mapOf("Statement" to continuedIndent())
            ),
            foldNodeProp.add(
                mapOf(
                    "Statement" to { tree, state ->
                        val lineEnd = state.doc.lineAt(tree.from).to
                        FoldRange(minOf(tree.from + 100, lineEnd), tree.to)
                    },
                    "BlockComment" to { tree, _ ->
                        FoldRange(tree.from + 2, tree.to - 2)
                    }
                )
            )
        )
    )
)

/**
 * Create an [LRLanguage] for a given [DialectSpec] by swapping in the dialect's tokenizer.
 */
internal fun sqlLanguageFor(dialectSpec: DialectSpec): LRLanguage {
    val dialectTokenizer = tokensFor(dialectSpec)
    return LRLanguage.define(
        parser = sqlParser.configure(
            ParserConfig(
                tokenizers = listOf(TokenizerReplacement(from = tokens, to = dialectTokenizer))
            )
        ),
        name = "sql"
    )
}
